//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelWarrant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelWarrant()
        {
            this.TravelRoute = new HashSet<TravelRoute>();
        }
    
        public int IDTravelWarrant { get; set; }
        public string Commander { get; set; }
        public int WarrantNumber { get; set; }
        public string StartPoint { get; set; }
        public string Destination { get; set; }
        public int QuantityOfDays { get; set; }
        public System.DateTime DateOfOpening { get; set; }
        public System.DateTime DateOfClosing { get; set; }
        public int DriverID { get; set; }
        public int VehicleID { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRoute> TravelRoute { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
